### ISSUE TITLE
Display what user just clicked for filtering

### ISSUE THREAD

**Issue by norrec99** [near-sighted/news-site#4]
it could be like this;

- ![Capture](https://user-images.githubusercontent.com/45902312/130570536-89a084dc-1044-49d8-9050-261a50953da3.PNG)

**Comment by humanman** [comment]
good call.

**Comment by humanman** [comment]
added highlighting - https://github.com/near-sighted/news-site/commit/fbc3d34f26bbb2e0c1c0368509973c0db49eac8b
